name: CalVer Tagging

on:
  push:
    branches:
      - main # or your main branch

jobs:
  tag:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # or latest version.

      - name: CalVer tag
        uses: Digital-Udvikling/actions-calver@v0.4.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
